In [22]:
import pandas as pd
import numpy as np

In [23]:
df_anp = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep=';')
df_anp

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36898,159,10,2025,2025m10,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,4.0,0.0,37,2,0,0,0,0,163,2
36899,165,10,2025,2025m10,33,5,Mangaratiba,3302601,Interior,1,...,4.0,0.0,21,0,0,0,0,0,196,2
36900,166,10,2025,2025m10,33,5,Angra dos Reis,3300100,Interior,3,...,12.0,0.0,82,8,0,1,0,0,682,2
36901,167,10,2025,2025m10,43,5,Paraty,3303807,Interior,1,...,2.0,1.0,11,1,0,0,0,0,195,2
36902,168,10,2025,2025m10,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,3,1,0,0,0,0,66,2

In [ ]:
df_rj_etanol = df_anp.loc[(df_anp['munic'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]
df_rj_etanol

KeyError: 'Municipio'

In [ ]:
df_rj_etanol['Valor de Venda'] = df_rj_etanol['Valor de Venda'].str.replace(',','.').astype(float)

C:\Users\ribeiro.renan\AppData\Local\Temp\ipykernel_30932\3668819183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rj_etanol['Valor de Venda'] = df_rj_etanol['Valor de Venda'].str.replace(',','.').astype(float)

In [ ]:
media_bairro_rj = df_anp_rj.groupby('Bairro')['Valor de Venda'].mean().reset_index()
media_bairro_rj = media_bairro_rj.sort_values(by='Valor de Venda', ascending=False)
media_bairro_rj

                      Bairro  Valor de Venda
73                   COTIARA        7.145417
237             SANTA IZABEL        6.960000
156                     MURY        6.886731
162  NOVA ANGRA (CUNHAMBEBE)        6.856667
174     PARQUE DAS PALMEIRAS        6.801458
..                       ...             ...
157                  MUTONDO        5.181803
64                 COLUBANDE        5.103854
44                   CAMARAO        4.994000
216               RAUL VEIGA        4.978800
4                   ABOLIÇÃO        4.427500

[285 rows x 2 columns]

In [ ]:
array_valor_venda = np.array(media_bairro_rj['Valor de Venda'])

In [ ]:
media = np.mean(array_valor_venda)
mediana = np.median(array_valor_venda)
q1 = np.quantile(array_valor_venda, 0.25)
q2 = np.quantile(array_valor_venda, 0.50)
q3 = np.quantile(array_valor_venda, 0.75)
iqr = q3 - q1
limite_s= q3 + 1.5*iqr
limite_i = q1 - 1.5*iqr

In [ ]:

print(f'A média é {media}')
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
print(f"O limite superior é {limite_s}")
print(f'O limite inferior é {limite_i}')

NameError: name 'media' is not defined

In [ ]:
bairro_acima_q3 = media_bairro_rj.loc[media_bairro_rj['Valor de Venda'] > q3]
bairro_acima_q3

                      Bairro  Valor de Venda
73                   COTIARA        7.145417
237             SANTA IZABEL        6.960000
156                     MURY        6.886731
162  NOVA ANGRA (CUNHAMBEBE)        6.856667
174     PARQUE DAS PALMEIRAS        6.801458
..                       ...             ...
29                    BINGEN        6.061500
163             NOVA NITEROI        6.061275
67             CONSERVATORIA        6.050000
154                    MORIN        6.039000
30               BOA FORTUNA        6.036300

[71 rows x 2 columns]

In [ ]:
outlier_furto_celular = df_furto_celular.loc[df_furto+outlier_furto_celular['furto_celular'] > limite_s ]